"""Programming quotes for startup banner."""

import random

QUOTES = [
    "Talk is cheap. Show me the code. - Linus Torvalds",
    "Programs must be written for people to read. - Harold Abelson",
    "Any fool can write code that a computer can understand. - Martin Fowler",
    "First, solve the problem. Then, write the code. - John Johnson",
    "The best error message is the one that never shows up. - Thomas Fuchs",
    "Make it work, make it right, make it fast. - Kent Beck",
    "Code is like humor. When you have to explain it, it's bad. - Cory House",
    "Simplicity is the soul of efficiency. - Austin Freeman",
    "Before software can be reusable it first has to be usable. - Ralph Johnson",
    "Java is to JavaScript what car is to carpet. - Chris Heilmann",
    "Testing leads to failure, and failure leads to understanding. - Burt Rutan",
    "The only way to learn a new language is by writing programs in it. - Dennis Ritchie",
    "Walking on water and developing software from a spec are easy if both are frozen. - Edward V. Berard",
    "If debugging is removing bugs, then programming is putting them in. - Edsger Dijkstra",
    "Don't worry if it doesn't work right. If everything did, you'd be out of a job. - Mosher's Law",
    "A language that doesn't affect how you think is not worth knowing. - Alan Perlis",
    "It's not a bug; it's an undocumented feature. - Anonymous",
    "Measuring progress by lines of code is like measuring aircraft progress by weight. - Bill Gates",
    "Always code as if the maintainer is a violent psychopath who knows where you live. - John Woods",
    "In theory, there is no difference between theory and practice. In practice, there is. - van de Snepscheut",
    "One of my most productive days was throwing away 1000 lines of code. - Ken Thompson",
    "The function of good software is to make the complex appear simple. - Grady Booch",
    "Programming is telling another human what one wants the computer to do. - Donald Knuth",
    "Optimism is an occupational hazard of programming: feedback is the treatment. - Kent Beck",
    "Deleted code is debugged code. - Jeff Sickel",
    "Controlling complexity is the essence of computer programming. - Brian Kernighan",
    "Copy-and-paste is a design error. - David Parnas",
    "Code you haven't looked at in six months might as well be someone else's. - Eagleson's Law",
    "The cheapest, fastest, and most reliable components are those that aren't there. - Gordon Bell",
    "When in doubt, use brute force. - Ken Thompson",
    "You can't have great software without a great team. - Jim McCarthy",
    "A good programmer looks both ways before crossing a one-way street. - Anonymous",
    "It works on my machine. - Every developer ever",
    "Unix is simple. It just takes a genius to understand its simplicity. - Dennis Ritchie",
    "I'm not a great programmer; I'm a good programmer with great habits. - Kent Beck",
    "Every great developer got there by solving problems they were unqualified to solve. - Patrick McKenzie",
    "Programming isn't about what you know; it's about what you can figure out. - Chris Pine",
    "Weeks of coding can save you hours of planning. - Anonymous",
    "Debugging is twice as hard as writing the code in the first place. - Brian Kernighan",
    "I choose a lazy person to do a hard job. They will find an easy way to do it. - Bill Gates",
    "Give a man a program, frustrate him for a day. Teach him to program, frustrate him for life. - Waseem",
    "Experience is the name everyone gives to their mistakes. - Oscar Wilde",
    "Don't do it. Don't do it yet. (Rules of Optimization) - Michael A. Jackson",
    "Premature optimization is the root of all evil. - Donald Knuth",
    "Nine people can't make a baby in a month. - Fred Brooks",
    "Without requirements or design, programming is adding bugs to an empty text file. - Louis Srygley",
    "If you think good architecture is expensive, try bad architecture. - Brian Foote",
    "Simplicity is prerequisite for reliability. - Edsger Dijkstra",
    "There are only two hard things: cache invalidation and naming things. - Phil Karlton",
    "Truth can only be found in one place: the code. - Robert C. Martin",
    "I don't care if it works on your machine! We are not shipping your machine! - Vidiu Platon",
    "The most dangerous phrase is 'We've always done it this way.' - Grace Hopper",
    "The sooner you start to code, the longer the program will take. - Roy Carlson",
    "Good code is its own best documentation. - Steve McConnell",
    "Fix the cause, not the symptom. - Steve Maguire",
    "Simplicity carried to the extreme becomes elegance. - Jon Franklin",
    "Everybody should learn to program because it teaches you how to think. - Steve Jobs",
    "It's harder to read code than to write it. - Joel Spolsky",
    "Documentation is a love letter that you write to your future self. - Damian Conway",
    "Adding manpower to a late software project makes it later. - Fred Brooks",
    "Programming is not about typing, it's about thinking. - Rich Hickey",
    "Shipping is a feature. A really important feature. - Joel Spolsky",
    "The best code is no code at all. - Jeff Atwood",
    "Bad programmers worry about the code. Good programmers worry about data structures. - Linus Torvalds",
    "Plan to throw one away; you will, anyhow. - Fred Brooks",
    "Software gets slower faster than hardware gets faster. - Wirth's Law",
    "We reject kings, presidents and voting. We believe in rough consensus and running code. - Dave Clark",
    "The purpose of software engineering is to control complexity, not to create it. - Pamela Zave",
    "Laziness, impatience, and hubris: the three virtues of a programmer. - Larry Wall",
    "The best way to predict the future is to implement it. - David Heinemeier Hansson",
    "Move fast and break things. Unless you are breaking stuff, you are not moving fast enough. - Zuckerberg",
    "The computer was born to solve problems that did not exist before. - Bill Gates",
    "Software and cathedrals are much the same; first we build them, then we pray. - Anonymous",
    "People think CS is the art of geniuses, but the actual reality is the opposite. - Donald Knuth",
    "The art of debugging is figuring out what you really told your program to do. - Andrew Singer",
    "Real programmers don't comment their code. If it was hard to write, it should be hard to read. - Anonymous",
    "You might not think programmers are artists, but programming is extremely creative. - John Romero",
    "How do you make a small fortune in software? Start with a large fortune. - Anonymous",
    "If we want users to like our software, we should design it to behave like a likeable person. - Alan Cooper",
    "The only truly secure system is one that is powered off, cast in concrete, and sealed in lead. - Gene Spafford",
    "There is no programming language that will prevent programmers from making bad programs. - Larry Flon",
    "Software is like entropy: it is difficult to grasp, weighs nothing, and always increases. - Norman Augustine",
    "The trouble with programmers is you can never tell what they're doing until it's too late. - Seymour Cray",
    "That's the thing about people who think they hate computers. They really hate lousy programmers. - Larry Niven",
    "Most good programmers do programming not because they expect to get paid, but because it is fun. - Linus Torvalds",
    "The most disastrous thing you can learn is your first programming language. - Alan Kay",
    "Perfection is achieved when there is nothing left to take away. - Antoine de Saint-Exupery",
    "Programming is the art of adding bugs to an empty text file. - Louis Srygley",
    "Every minute spent on CI is ten minutes saved in debugging. - Anonymous",
    "Should array indices start at 0 or 1? My compromise of 0.5 was rejected. - Stan Kelly-Bootle",
    "The computing scientist's main challenge is not to get confused by his own making. - Dijkstra",
    "The best performance improvement is the transition from nonworking to working. - J. Osterhout",
    "Any sufficiently advanced bug is indistinguishable from a feature. - Rich Kulawiec",
    "Code never lies, comments sometimes do. - Ron Jeffries",
    "The only way to go fast, is to go well. - Robert C. Martin",
    "Beware of bugs in the above code; I have only proved it correct, not tried it. - Donald Knuth",
    "The Internet? Is that thing still around? - Homer Simpson",
    "Never trust a computer you can't throw out a window. - Steve Wozniak",
    "On the Internet, nobody knows you're a dog. - Peter Steiner",
    "There is no cloud. It's just someone else's computer. - Anonymous",
]


def get_random_quote() -> str:
    """Return a random programming quote."""
    return random.choice(QUOTES)
